### ISSUE TITLE
inconsistent default image filenames

### ISSUE THREAD

**Issue by dowcet** [tokland/pysheng#17]
If I download part of a book by CLI into `~/folder/`, Pysheng creates a new folder `Author - Title` and uses short filenames like so: `~/folder/Author - Title/001.png`. If I then try to continue downloading more pages from the same book to `~/folder`, I would expect it to continue where it left off by downloading to `~/folder/Author - Title/002.png` or whatever.  (I think the CLI works like that? I'm not sure if it skips or overwrites existing files... But anyway, here's the main issue I wanted to document... )

If I continue using the GUI instead of the CLI, it doesn't use the subfolder. I get filenames like `~/folder/Author - Title 02.png`. It would be more convenient and predictable if both the CLI and GUI both used the subfolder and shorter filenames.

**Comment by tokland** [comment]
indeed, try a15167c
